# Repo info
owner: N3uralCreativity
repo: upptime

# Make requests consistent (also helps with Cloudflare rules)
user-agent: upptime.js.org

sites:
  - name: Atelier YO
    url: https://atelier-yo.fr
    headers:
      - "User-Agent: upptime.js.org"

  - name: Atelier YO (www)
    url: https://www.atelier-yo.fr
    headers:
      - "User-Agent: upptime.js.org"

status-website:
  # Hosted on GitHub Pages: https://n3uralcreativity.github.io/upptime/
  baseUrl: /upptime

  # Branding (use your site's favicon for a clean, legit look)
  name: Atelier YO — Status
  logoUrl: https://atelier-yo.fr/favicon.ico
  favicon: https://atelier-yo.fr/favicon.ico

  # Header text
  introTitle: "Atelier YO — Service Status"
  introMessage: "Live uptime, incidents, and response-time history for atelier-yo.fr."

  # Navigation
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://atelier-yo.fr
    - title: Incidents
      href: https://github.com/$OWNER/$REPO/issues
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Optional: you can add notifications later (Discord, email, etc.)
