# Change these first
owner: N3uralCreativity
repo: upptime

# Make the User-Agent predictable (Cloudflare will see this)
user-agent: Mozilla/5.0 (Upptime)

sites:
  - name: Atelier YO (Main)
    url: https://atelier-yo.fr
    headers:
      - "User-Agent: upptime.js.org"

  - name: Atelier YO (www)
    url: https://www.atelier-yo.fr
    headers:
      - "User-Agent: upptime.js.org"

status-website:
  # No custom domain for the status page:
  # (status page will be at https://n3uralcreativity.github.io/upptime/)
  baseUrl: /upptime

  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Atelier YO Status
  introTitle: "**Atelier YO — Status**"
  introMessage: Live uptime and incident updates for **atelier-yo.fr**.
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://atelier-yo.fr
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
