# Core
owner: N3uralCreativity
repo: upptime

# Keep this containing "uptime.js.org" since your Cloudflare rule is matching it
user-agent: uptime.js.org

sites:
  - name: Atelier YO
    url: https://atelier-yo.fr
    icon: https://atelier-yo.fr/favicon.ico
  - name: Atelier YO (www)
    url: https://www.atelier-yo.fr
    icon: https://atelier-yo.fr/favicon.ico

status-website:
  # Custom domain
  cname: status.atelier-yo.fr

  # Branding
  name: Atelier YO — Status
  introTitle: "Atelier YO — Service status"
  introMessage: "Live uptime + incident history for **atelier-yo.fr**."

  # These 2 only work AFTER you add the files into /assets (next section)
  logoUrl: /logo.svg
  themeUrl: /atelier-yo-theme.css

  navbar:
    - title: Status
      href: /
    - title: Main website
      href: https://atelier-yo.fr
    - title: Incidents
      href: /history
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

  metaTags:
    - name: "theme-color"
      content: "#0b1220"
    - name: "color-scheme"
      content: "dark light"

  customHeadHtml: >
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
