# Core
owner: N3uralCreativity
repo: upptime
user-agent: upptime.atelier-yo.fr

sites:
  - name: Atelier YO
    url: https://atelier-yo.fr
    icon: https://atelier-yo.fr/favicon.ico
    headers:
      - "User-Agent: upptime.atelier-yo.fr"

  - name: Atelier YO (www)
    url: https://www.atelier-yo.fr
    icon: https://atelier-yo.fr/favicon.ico
    headers:
      - "User-Agent: upptime.atelier-yo.fr"

status-website:
  # Custom domain
  cname: status.atelier-yo.fr

  # Branding
  name: Atelier YO — Status

  # IMPORTANT: load assets from GitHub Pages (reliable)
  logoUrl: https://n3uralcreativity.github.io/upptime/assets/logo.svg
  faviconSvg: https://n3uralcreativity.github.io/upptime/assets/logo.svg

  # Theme CSS (also from GitHub Pages)
  themeUrl: https://n3uralcreativity.github.io/upptime/assets/atelier-yo-theme.css

  introTitle: "Atelier YO — Service status"
  introMessage: "Live uptime + incident history for **atelier-yo.fr**."

  navbar:
    - title: Status
      href: /
    - title: Main website
      href: https://atelier-yo.fr
    - title: Incidents
      href: /history
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

  # Optional extra meta
  metaTags:
    - name: "theme-color"
      content: "#0b1220"
    - name: "color-scheme"
      content: "dark light"

  # Optional: nicer font
  customHeadHtml: >
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
